### ISSUE TITLE
DatabaseManager._isTableExists shouldn't be used apart from it's assembly

### ISSUE THREAD

**Issue by Lakasabasz** [JakubJKrawczyk/ProgramSaldo-TheWayOfDapper#13]
It was easier to test when it was `public` but it was mistake. Fixed to `internal`, but if you need function like it I'll leave issue open.

**Comment by JakubJKrawczyk** [comment]
I need function like that to check if table for specific month exists

**Comment by Lakasabasz** [comment]
Will be added in next sprint
